version: "3"
services:
  jmix-crm:
    image: jmix-crm
    build:
      context: .
    user: root
    volumes:
      - jmix:/workspace/.jmix
    ports:
      - "8080:8080"
    environment:
      - SPRING_AI_OPENAI_APIKEY=${SPRING_AI_OPENAI_APIKEY}
volumes:
  jmix: