package com.company.crm.ai.view.context;

import com.company.crm.AbstractUiTest;
import com.company.crm.ai.model.AiAttachmentOrigin;
import com.company.crm.ai.model.AiConversation;
import com.company.crm.ai.model.AiConversationAttachment;
import com.company.crm.ai.model.ChatMessage;
import com.company.crm.ai.model.ChatMessageEntityReference;
import com.company.crm.ai.model.ChatMessageType;
import com.company.crm.ai.view.component.card.AiAttachmentCard;
import com.company.crm.ai.view.component.card.AiConversationContextCardFactory;
import com.company.crm.ai.view.component.card.AiEntityReferenceCard;
import com.company.crm.model.client.Client;
import com.company.crm.model.invoice.Invoice;
import com.company.crm.model.invoice.InvoiceStatus;
import com.company.crm.model.order.Order;
import com.company.crm.model.order.OrderStatus;
import com.vaadin.flow.component.html.H5;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import io.jmix.core.FileRef;
import io.jmix.core.Id;
import io.jmix.core.IdSerialization;
import io.jmix.core.Metadata;
import io.jmix.flowui.UiComponents;
import io.jmix.flowui.component.sidepanellayout.SidePanelLayout;
import io.jmix.flowui.view.MessageBundle;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Autowired;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class ConversationContextSidePanelRendererTest extends AbstractUiTest {

    @Autowired
    private UiComponents uiComponents;

    @Autowired
    private Metadata metadata;

    @Autowired
    private IdSerialization idSerialization;

    @Autowired
    private ObjectProvider<MessageBundle> messageBundles;

    @Test
    void rendersSectionsAndCardsForRealEntityReferencesAndAttachments() {
        Client client = entities.client("Context Panel Client");
        Order order = entities.order(client, LocalDate.of(2026, 5, 20), OrderStatus.NEW, BigDecimal.valueOf(1200));
        Invoice invoice = entities.invoice(client, order, BigDecimal.valueOf(1200), InvoiceStatus.NEW, LocalDate.of(2026, 5, 21));
        invoice.setNumber("INV-CONTEXT-" + UUID.randomUUID());
        invoice = saveWithoutReload(invoice);

        AiConversation conversation = createAndSaveEntity(AiConversation.class, conv -> conv.setTitle("Context rendering"));
        ChatMessage message = createAndSaveEntity(ChatMessage.class, msg -> {
            msg.setConversation(conversation);
            msg.setType(ChatMessageType.USER);
            msg.setContent("Show context");
        });

        ChatMessageEntityReference clientReference = entityReference(message, idSerialization.idToString(Id.of(client)), 0);
        ChatMessageEntityReference invoiceReference = entityReference(message, idSerialization.idToString(Id.of(invoice)), 1);
        AiConversationAttachment generatedAttachment = attachment(message, "generated-report.pdf", AiAttachmentOrigin.AI_GENERATED);
        AiConversationAttachment uploadedAttachment = attachment(message, "uploaded-context.csv", AiAttachmentOrigin.USER_UPLOADED);

        message.setEntityReferences(List.of(clientReference, invoiceReference));
        message.setAttachments(List.of(generatedAttachment, uploadedAttachment));
        conversation.setMessages(List.of(message));

        VerticalLayout container = new VerticalLayout();
        SidePanelLayout sidePanelLayout = uiComponents.create(SidePanelLayout.class);
        ConversationContextSidePanelRenderer renderer = new ConversationContextSidePanelRenderer(
                conversationMessageBundle(),
                new ConversationContextAggregator(),
                new AiConversationContextCardFactory(uiComponents, metadata, ignored -> {
                }, ignored -> {
                })
        );

        renderer.render(container, sidePanelLayout, conversation);

        String invoiceNumber = invoice.getNumber();
        assertThat(viewTestSupport.texts(container, H5.class)).contains(
                "Referenced entities",
                "Generated by CRM AI",
                "Uploaded"
        );
        assertThat(viewTestSupport.textsByClassName(container, "ai-timeline-attachment-title"))
                .contains("Context Panel Client", "generated-report.pdf", "uploaded-context.csv")
                .anySatisfy(title -> assertThat(title).contains(invoiceNumber));
        assertThat(viewTestSupport.descendants(container, AiEntityReferenceCard.class)).hasSize(2);
        assertThat(viewTestSupport.descendants(container, AiAttachmentCard.class)).hasSize(2);
    }

    private MessageBundle conversationMessageBundle() {
        MessageBundle messageBundle = messageBundles.getObject();
        messageBundle.setMessageGroup("com.company.crm.ai.view.conversation");
        return messageBundle;
    }

    private ChatMessageEntityReference entityReference(ChatMessage message, String serializedId, int sortOrder) {
        ChatMessageEntityReference reference = createAndSaveEntity(ChatMessageEntityReference.class, ref -> {
            ref.setMessage(message);
            ref.setEntityReference(serializedId);
            ref.setSortOrder(sortOrder);
        });
        return reference;
    }

    private AiConversationAttachment attachment(ChatMessage message, String fileName, AiAttachmentOrigin origin) {
        return createAndSaveEntity(AiConversationAttachment.class, attachment -> {
            attachment.setMessage(message);
            attachment.setFile(new FileRef("storage", "test/" + fileName, fileName));
            attachment.setFileName(fileName);
            attachment.setTitle(fileName);
            attachment.setOrigin(origin);
        });
    }
}
